spring.application.name=shopsphere-auth-service

server.port=8087

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere_auth_service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Token Configuration
token.key-ID=${KEY_ID:auth-service-key-1}
token.private-key-path=${PRIVATE_KEY_PATH}
token.public-key-path=${PUBLIC_KEY_PATH}
# units in minutes
token.access-expiration=${ACCESS_EXPIRATION:15}
token.refresh-expiration=${REFRESH_EXPIRATION:10080}
